[app]
name = "mcenter"
key  = "this is your app key"

[app.http]
host = "127.0.0.1"
port = 8010

[app.grpc]
host = "127.0.0.1"
port = 18010

[mongodb]
endpoints = ["127.0.0.1:27017"]

[log]
level = "debug"

[log.file]
enable = true
file_path = "logs/app.log"

[jaeger]
endpoint = "http://localhost:14268/api/traces"